a_second/urls.py
from os import name
from django.urls import path
from . import views

app_name = "a_second"

urlpatterns = [
    path("clock/", views.clock, name="clock"),
    path("", views.input, name="input")
]

hybridart/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("a_second.urls"))
]

a_second/models.py
from django.db import models

# Create your models here.
class Clock(models.Model):
    second = models.FloatField()
    user = models.CharField(max_length=100, blank=True,null=True)

a_second/forms.py
from django.forms import ModelForm, fields
from django.forms.models import model_to_dict
from .models import Clock

class ClockForm(ModelForm):
    class Meta:
        model = Clock
        fields = ["second"]

a_second/views.py
from django.shortcuts import redirect, render
from .models import Clock
from .forms import ClockForm
import json
# Create your views here.
def clock(request):
    clock_query_set = Clock.objects.all()
    clock_list = list(clock_query_set.values())
   
    return render(request, "a_second/index2.html",{"data_json": json.dumps(clock_list)})

def input(request):
    if request.method == "POST":
        print(request.POST)
        form = Clock.objects.create(second=float(request.POST["second"]))
        form.save()
        return redirect("a_second:clock")
    else:
        form = ClockForm
    return render(request, "a_second/form.html", {"form": form})

a_second/templates/a_second/form.html
{% load static %}

<html>
    <head>
    <link rel="stylesheet" href="{% static 'css/form.css'%}">
    </head>
    <body class="light">
        <div>
        <h1>a second.</h1>
        <p class="contact-text place">
            Press the start button and measure 「your」 10 seconds.
        </p>
        </div>
        <div>
        <form name="form1" id="form1" action="{% url 'a_second:input' %}" method="POST">
            {% csrf_token %}
            
            <input type="hidden" name="second" value="">
            <button type="button" id="btnStart" onclick="startStop()">
                
                start
                
            </button>
            
            <button type="button" id="btnClear" onclick="resetStopWatch()">
            
                clear
            
            </button>

            <button type="button"disabled id="btnPost" onclick="post_second()">
            ok
            
            </button>

            
        </form>
        </div>
    </body>
    <script>
        // -------------------------------------------------------------------------
            // stopWatch.js ストップウォッチプログラム
            //
            //		1970年1月1日からの経過時間（ミリ秒単位）を使っている
            //
            // 					created at 2014-06-26 on take3.asia
            // -------------------------------------------------------------------------

            var mode;					// ストップウォッチのモード	RUN/STOP
            var startTime;				// スタートした時刻
            var nowTime;				// ストップした時刻
            var addTime;				// 経過時間（ストップウォッチ再開時に加算する）
            var millisec;					// 1000分の1秒
            var sec100;					// 100分の1秒
            var sec;						// 秒
            var min;						// 分
            var hour;					// 時
            var gmt;						// タイムゾーンのオフセット値
            //	例）GMT+0900 なら 標準時より9時間後をさしているので-9する
            var timerId;					// タイマー
            var time //postする値
            /*
             * 定数
             */
            var RUN = 1;				// 動作中
            var STOP = 0;				// 停止中

            /*
             * ストップウォッチのリセット
             */
            function resetStopWatch() {
                mode = STOP;
                addTime = 0;
                millisec = sec100 = sec = min = hour = 0;
                gmt = new Date().getTimezoneOffset() / 60;	// 戻り値は分のため60で割る
                //document.getElementById("time").innerHTML = "00:00:00.00";
                document.getElementById("btnStart").disabled = "";	
                document.getElementById("btnPost").disabled = "true";		// クリアボタンを使用可
                
            }

            /*
             * ボタン処理
             */
            function startStop() {
                switch (mode) {
                    case STOP:		// スタートを押したとき
                        resetStopWatch()
                        mode = RUN;
                        
                        timerId = setTimeout(runStopWatch, 10);
                        document.getElementById("btnClear").disabled = "true";	// クリアボタンを使用不可
                        document.getElementById("btnStart").innerHTML = "stop";
                     // スタート時刻を設定（ストップウォッチが進んでいれば加算）
                     startTime = new Date().getTime();
                     addTime = (hour * 60 * 60 * 1000 + min * 60 * 1000 + sec * 1000 + millisec);
                     startTime -= addTime;
                     break;
               case RUN:		// ストップを押したとき
                     mode = STOP;
                     clearTimeout(timerId);
                     //			nowTime = new Date().getTime();
                     document.getElementById("btnStart").innerHTML = "start";
                     document.getElementById("btnStart").disabled = "true";	
                     document.getElementById("btnClear").disabled = "";		// クリアボタンを使用可
                     document.getElementById("btnPost").disabled = "";		// クリアボタンを使用可
                    
                     drawTime();
             }
         }
       /*
          * 時間表示
          */
         function drawTime() {
             var strTime = "";
             var strSec100, strSec, strMin, strHour;
           // 数値を文字に変換及び2桁表示設定
             strSec100 = "" + sec100;
             if (strSec100.length < 2) {
                 strSec100 = "0" + strSec100;
             }
             strSec = "" + sec;
             if (strSec.length < 2) {
                 strSec = "0" + strSec;
             }
             strMin = "" + min;
             if (strMin.length < 2) {
                 strMin = "0" + strMin;
             }
             strHour = "" + hour;
             if (strHour.length < 2) {
                 strHour = "0" + strHour;
             }
             // 表示形式を設定
             strTime = strHour + ":" + strMin + ":" + strSec + "." + strSec100;
             //document.getElementById("time").innerHTML = strTime;
         }
       /*
          * 時間計測
          */
         function runStopWatch() {
             // スタートからの差分をとる
             nowTime = new Date().getTime();
             diff = new Date(nowTime - startTime);
             // ミリ秒、100分の1秒、秒、分、時を設定
             millisec = diff.getMilliseconds();
             sec100 = Math.floor(millisec / 10);
             sec = diff.getSeconds();
             min = diff.getMinutes();
             hour = diff.getHours() + gmt;	// タイムゾーンのオフセットを考慮する
             time = diff.getMilliseconds()/1000+diff.getSeconds();
           drawTime();			// 時間表示
             timerId = setTimeout(runStopWatch, 10);
         }
       /*
          * 実行時の処理
          */
         window.onload = function () {
             resetStopWatch();
         }

         function post_second(){
            document.forms.form1.second.value = time/10.0;
            var f = document.forms["form1"];
            f.method = "POST";
            f.submit();
            return true;
         }
  </script>
</html>

a_second/templates/a_second/index.html
{% load static %}

<html>

<head>
    <title>a second</title>
    <link rel="stylesheet" href="{% static 'css/clock.css'%}">

</head>

<body class="">


    <div>
        <div class="clocklist">

        </div>
    </div>
</body>

<script type="text/javascript">
    const data = JSON.parse('{{ data_json|safe }}');
    console.log(data);
    const deg = 6;
    // 360 / (12 * 5);
    var day = new Date();
    var hh = day.getHours() * 30;
    var mm = day.getMinutes() * deg;
    var ss = day.getSeconds() * deg;
    var clock_list = [];
    var hh_list = [];
    var mm_list = [];
    var ss_list = [];
    for (var i = 0; i < data.length; i++) {
        hh_list.push(hh);
        mm_list.push(mm);
        ss_list.push(ss);
    }
    var hr_list = [];
    var mn_list = [];
    var sc_list = [];
    var audioElem_list = [];
    var audioElem1 = new Audio();
    var audioElem2 = new Audio();
    var audioElem3 = new Audio();
    var audioElem4 = new Audio();
    audioElem1.src = "{% static 'src/clock.mp3' %}";
    audioElem2.src = "{% static 'src/clock2.mp3' %}";
    audioElem3.src = "{% static 'src/clock3.mp3' %}";
    audioElem4.src = "{% static 'src/clock4.mp3' %}";
    var audioElements = [];
    audioElements.push(audioElem1);
    audioElements.push(audioElem2);
    audioElements.push(audioElem3);
    audioElements.push(audioElem4);
    for (var key in data) {
        console.log(data[key])
        var a_second = data[key]["second"];
        var clock = document.createElement("div");
        clock.classList.add("clock");
        var hr = document.createElement("div");
        hr.classList.add("hr");
        var mn = document.createElement("div");
        mn.classList.add("mn");
        var sc = document.createElement("div");
        sc.classList.add("sc");
        hr_list.push(hr);
        mn_list.push(mn);
        sc_list.push(sc);
        audioElem_list.push(audioElements[Math.floor(Math.random() * 4)]);
        var a = setInterval(move_clock, a_second * 1000, key);
        console.log("timer_id", a);
        clock.appendChild(hr);
        clock.appendChild(mn);
        clock.appendChild(sc);
        var clocklist = document.querySelector(".clocklist");
        clocklist.appendChild(clock);
        function toggleClass() {
            const body = document.querySelector('body');
            body.classList.toggle('light');
            body.style.transition = `0.3s linear`;
        }
    }
    function move_clock(key) {
        var hh = hh_list[key];
        var mm = mm_list[key];
        var ss = ss_list[key];
        hr = hr_list[key];
        mn = mn_list[key];
        sc = sc_list[key];
        ss = ss + deg;
        audioElem_list[key].play();
        console.log("ss:" + ss);
        if (ss % 360 == 0) {
            console.log("minute");
            mm = mm + deg;
            if (mm % 360 == 0) {
                hh = hh + 30;
            }
        }
        hr.style.transform = `rotateZ(${hh}deg)`;
        mn.style.transform = `rotateZ(${mm}deg)`;
        sc.style.transform = `rotateZ(${ss}deg)`;
        hh_list[key] = hh;
        mm_list[key] = mm;
        ss_list[key] = ss;
        hr_list[key] = hr;
        mn_list[key] = mn;
        sc_list[key] = sc;
    }
</script>
</body>

</html>

a_second/templates/a_second/index2.html
{% load static %}

<html>

<head>
    <title>a second</title>
    <link rel="stylesheet" href="{% static 'css/clock.css'%}">

</head>

<body class="">


    <div>
        <div class="clocklist">

        </div>
    </div>
</body>

<script type="text/javascript">
    class ClockHands {
        constructor(time,tag) {
            this.time = time;
            this.deg = 6;
            this.tag = tag;
            this.div =  document.createElement("div");
            // 360 / (12 * 5);
        }
        putAhead() {
            pass;
        }
        
        addClassList(){
            this.div.classList.add(this.tag);
        }
    }
    class HourClockHands extends ClockHands {
        constructor(time,tag) {
            super();
            this.time = time * this.deg * 5;
        }
        putAhead() {
            this.time += this.deg * 5;
        }
    }

    class MinuteClockHands extends ClockHands {
        constructor(time,tag) {
            super();
            this.time = time * this.deg;
        }
        putAhead() {
            this.time += this.deg;
        }
    }


    class SecondClockHands extends ClockHands {
        constructor(time,tag) {
            super();
            this.time = time * this.deg;

        }
        putAhead() {
            this.time = this.time + this.deg;
        }
    }


    const data = JSON.parse('{{ data_json|safe }}');
    console.log(data);
    //const deg = 6;
    // 360 / (12 * 5);
    var day = new Date();
    var clock_list = [];
    var hh_list = [];
    var mm_list = [];
    var ss_list = [];
    for (var i = 0; i < data.length; i++) {
        var initial_hh = new HourClockHands(day.getHours(),"hr");
        var initial_mm = new MinuteClockHands(day.getMinutes(),"mn");
        var initial_ss = new SecondClockHands(day.getSeconds(),"sc");
        hh_list.push(initial_hh);
        mm_list.push(initial_mm);
        ss_list.push(initial_ss);
    }

    var hr_list = [];
    var mn_list = [];
    var sc_list = [];
    var audioElem_list = [];
    var audioElem1 = new Audio();
    var audioElem2 = new Audio();
    var audioElem3 = new Audio();
    var audioElem4 = new Audio();
    audioElem1.src = "{% static 'src/clock.mp3' %}";
    audioElem2.src = "{% static 'src/clock2.mp3' %}";
    audioElem3.src = "{% static 'src/clock3.mp3' %}";
    audioElem4.src = "{% static 'src/clock4.mp3' %}";
    var audioElements = [];
    audioElements.push(audioElem1);
    audioElements.push(audioElem2);
    audioElements.push(audioElem3);
    audioElements.push(audioElem4);

    for (var key in data) {
        console.log(data[key])
        var num = key;
        var a_second = data[num]["second"];


        var clock = document.createElement("div");
        clock.classList.add("clock");

        var hr = document.createElement("div");
        hr.classList.add("hr");

        var mn = document.createElement("div");
        mn.classList.add("mn");

        var sc = document.createElement("div");
        sc.classList.add("sc");


        hr_list.push(hr);
        mn_list.push(mn);
        sc_list.push(sc);

        audioElem_list.push(audioElements[Math.floor(Math.random() * 4)]);



        var a = setInterval(move_clock, a_second * 1000, num);
        console.log("timer_id", a);
        clock.appendChild(hr);
        clock.appendChild(mn);
        clock.appendChild(sc);

        var clocklist = document.querySelector(".clocklist");
        clocklist.appendChild(clock);


        function toggleClass() {
            const body = document.querySelector('body');
            body.classList.toggle('light');
            body.style.transition = `0.3s linear`;
        }
    }


    function move_clock(num) {
        var _hh = new HourClockHands();
        _hh = hh_list[num];

        var _mm = new MinuteClockHands();
        _mm = mm_list[num];

        var _ss = new SecondClockHands();
        _ss = ss_list[num];

        hr = hr_list[num];
        mn = mn_list[num];
        sc = sc_list[num];
        console.log("num:" + num);
        console.log("ss_list[num].time" + ss_list[num].time);
        console.log("ss_list[num].deg" + ss_list[num].deg);
        _ss.putAhead();
        audioElem_list[num].play();
        //console.log("ss:" + ss.time);
        if (_ss.time % 360 == 0) {
            console.log("minute");
            _mm.putAhead()

            if (_mm.time % 360 == 0) {
                _hh.putAhead()
            }
        }

        hr.style.transform = `rotateZ(${_hh.time}deg)`;
        mn.style.transform = `rotateZ(${_mm.time}deg)`;
        sc.style.transform = `rotateZ(${_ss.time}deg)`;

        hh_list[num] = _hh;
        mm_list[num] = _mm;
        ss_list[num] = _ss;
        hr_list[num] = hr;
        mn_list[num] = mn;
        sc_list[num] = sc;
    }
</script>
</body>

</html>